# Generated by Django 3.0.2 on 2020-04-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='classes',
            field=models.CharField(default='None', max_length=400),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='helped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.URLField(default='https://source.unsplash.com/random/200×200/?fruit'),
        ),
    ]
