# Generated by Django 3.0.2 on 2020-03-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_tutor',
        ),
    ]
