# Generated by Django 3.0.2 on 2020-04-11 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date account created'),
        ),
    ]
