# Generated by Django 3.0.2 on 2020-02-20 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='last_signin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last sign-in'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='0000000', max_length=200, primary_key=True, serialize=False),
        ),
    ]
