# Generated by Django 3.0.2 on 2020-03-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_userprofile_is_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
