# Generated by Django 3.0.2 on 2020-03-01 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200220_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
