# Generated by Django 3.0.2 on 2020-04-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_location'),
        ('login', '0002_remove_userprofile_date_created'),
    ]

    operations = [
    ]
