# Generated by Django 3.0.2 on 2020-04-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
