# Generated by Django 3.0.2 on 2020-03-02 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 19, 48, 56, 870600, tzinfo=utc), verbose_name='date created'),
        ),
    ]
