# Generated by Django 3.0.2 on 2020-03-02 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200302_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 19, 51, 29, 337125, tzinfo=utc), verbose_name='date created'),
        ),
    ]
