# Generated by Django 3.0.2 on 2020-04-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_userprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_num',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
