# Generated by Django 3.0.2 on 2020-04-22 02:53

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200421_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
