# Generated by Django 3.0.2 on 2020-03-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200302_1452'),
        ('login', '0004_userprofiles'),
    ]

    operations = [
    ]
