# Generated by Django 3.0.2 on 2020-04-22 03:39

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200421_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
