# Generated by Django 3.0.2 on 2020-03-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20200322_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lname',
            new_name='last_name',
        ),
    ]
