# Generated by Django 3.0.2 on 2020-03-22 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200322_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 18, 27, 59, 402359, tzinfo=utc), verbose_name='date account created'),
        ),
    ]
