# Generated by Django 3.0.2 on 2020-04-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tutor_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=31)),
                ('classes', models.CharField(default='None', max_length=400)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('helped', models.BooleanField(default=False)),
            ],
        ),
    ]
