# Generated by Django 3.0.2 on 2020-04-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tutor_request',
        ),
    ]
